### ISSUE TITLE
Disable buttons, don't hide them

### ISSUE THREAD

**Issue by mtedeschi** [WorldBank-Transport/DRIVER#170]
In some places, particularly the "add" accident view, we're hiding buttons instead of disabling them. We really should set them to be disabled instead of just removing them from the UI (this causes weird styling, and also isn't a best practice).

Is currently...
<img width="902" alt="screen shot 2015-10-05 at 4 29 48 pm" src="https://cloud.githubusercontent.com/assets/842387/10292667/81ab0700-6b7e-11e5-9da2-66af0ab5622d.png">

Should be...
<img width="390" alt="screen shot 2015-10-05 at 4 30 10 pm" src="https://cloud.githubusercontent.com/assets/842387/10292670/84f359b2-6b7e-11e5-9e58-59729cf704f1.png">

**Comment by kshepard** [comment]
This may be a bit difficult to fix: this interface is generated using an external library (json-editor). In order to make javascript styling changes to this section, we would probably need to fork the repo and make changes to it. This applies to both the add/edit record views and the entire Ashlar editor interface for building schemas.

**Comment by mtedeschi** [comment]
I'll restyle the buttons to work without having to do that—sounds like a lot of work.

**Comment by kshepard** [comment]
Sounds great to me, thanks.
