### ISSUE TITLE
Upon loading map page, it doesn't zoom to the selected polygon

### ISSUE THREAD

**Issue by kshepard** [WorldBank-Transport/DRIVER#209]
To reproduce:
 * Load dashboard page
 * Select polygon
 * Browse to map -- it doesn't zoom to the selected polygon

**Comment by ddohler** [comment]
This is intentional, although I agree it's a bit awkward: The map page keeps track of its most recent location and zoom, and we didn't want selecting a polygon on a different page to override that. I actually had implemented functionality to zoom on page load, but removed it after @flibbertigibbet pointed out that it would make the map's location-memory feature redundant. This might be a good thing for @jbranigan and @mtedeschi to look at because it seems like the functionality may be pulling user expectations in different directions.

**Comment by kshepard** [comment]
Oh, ok, that's a good point. Yeah, we'll have to talk through a good approach, as it seemed a bit unexpected at first.

**Comment by jbranigan** [comment]
Changing the primary geography should actually update the map state.

**Comment by flibbertigibbet** [comment]
My concern with state vs zooming to region is that it should only do one or the other and not both upon loading, depending on which is appropriate.

**Comment by jbranigan** [comment]
In the wireframes, a user logs in and chooses their primary geography before even hitting the dashboard page. It's kind of a constant theme across the app. I don't understand where the problem is.
