### ISSUE TITLE
Remove crossorigin.me workaround when pickpoint.io is fixed

### ISSUE THREAD

**Issue by jbranigan** [WorldBank-Transport/DRIVER#292]
Getting errors on this today on both reverse geocoding and search:

```XMLHttpRequest cannot load https://pickpoint.io/api/v1/reverse?format=json&key=jyp6mRMm__hsd7SqbFKF&lat=14.392118083661728&lon=120.90110778808594. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://prs.azavea.com' is therefore not allowed access. The response had HTTP status code 404.```

**Comment by kshepard** [comment]
I'll take a look at this.

**Comment by kshepard** [comment]
Looks like this isn't working because the request for OPTIONS on the endpoint is returning a 404:

curl -X OPTIONS 'https://pickpoint.io/api/v1/reverse?format=json&key=MYKEY'
{"status":"404","error":"Not Found"}

This OPTIONS request is required in order for the browser to be able to initiate a CORS request. I've emailed pickpoint.io support with the details. In the meantime, there's not too much we can do unless we wanted to move the call to pickpoint.io over to the server-side and proxy requests through django.

**Comment by kshepard** [comment]
Workaround implemented in: #293. I changed the title of this issue accordingly so we remember to remove the workaround when pickpoint.io is fixed.

**Comment by kshepard** [comment]
This was fixed on pickpoint.io a little while back, and the workaround was removed.
