### ISSUE TITLE
AUFS storage driver results in zombie processes

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#412]
See docker/docker#18180.

Java processes in Debian container hang seemingly at random, pegging CPU; container cannot be stopped. Issue only appeared when running container within vagrant, mounting volumes shared via NFS.

Switching storage driver to `devicemapper` fixes the issue; however, `devicemapper` also apparently causes file system corruption and [nasal demons](https://meta.discourse.org/t/cant-install-discourse-with-only-10-gb-disk-run-out-of-space/29149/36).

**Comment by hectcastro** [comment]
This was addressed in the MMW project with https://github.com/WikiWatershed/model-my-watershed/commit/6fb93e6bae9c71d339d660c421b5852438531df9.

**Comment by flibbertigibbet** [comment]
Ok. Any reason why the [AUFS dependencies install](https://github.com/azavea/ansible-docker/blob/develop/tasks/main.yml#L14) in the base ansible-docker role shouldn't be handling the kernel backport?

**Comment by hectcastro** [comment]
I think because it was only occurring on that instance of Docker/AUFS. There are a few other setups with that combo that are working fine.

My hope is that the patched kernel will be available soon. For DRIVER, adding the backported kernel install to the top level playbook may be the best bet for now. Once I see the patch kernel land, I'll open PRs against DRIVER and MMW to remove it.

**Comment by flibbertigibbet** [comment]
Ok, I'll go with a kernel backport on this project then.
