### ISSUE TITLE
SA - Save Button Grayed Out, Couldn't Save Changes

### ISSUE THREAD

**Issue by tgilcrest** [WorldBank-Transport/DRIVER#545]
When making changes in the schema editor to Incident Details, we saved our progress by hitting save at the bottom of the page.  Then, after we had made more changes, we went to save the changes but the Save button was grayed out so we couldn't save these new changes.

We were on an iPad using the Chrome browser.  We tried briefly to reproduce this by making changes, saving, and making more changes, but we could then save the changes.  I'd like to try to reproduce this with more testing.

**Comment by kshepard** [comment]
The only time the `Save` button is greyed out is when the form doesn't validate. For instance, if you added a field and never gave it a title it will save `Value required` in red next to the field and the `Save` button is disabled. I suspect that's what happened, but if you happen to find a case where it happens when the form appears to be valid, please post the details.

**Comment by kshepard** [comment]
Closing this. We can reopen if it is able to reproduced.
