### ISSUE TITLE
Web app does not run on root without manual start

### ISSUE THREAD

**Issue by flibbertigibbet** [WorldBank-Transport/DRIVER#84]
After provisioning, the editor app is running, but the web app does not run without executing the `grunt.sh` script from the host to serve it.

**Comment by ddohler** [comment]
I did some digging with some help from @CloudNiner and this is a two-part problem:
- nginx is returning `/index.html` when it should be returning a 404 (Looks like the fix here is for the `try_files` stanza to end with `=404;` rather than `index.html`).
- The minification process isn't handling the view partials correctly, so nginx falls back to returning `index.html`, which tries to load the view partials again, ad infinitum.
